name: Hello World Workflow

on: 
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Print Hello World
        run: echo "Hello World!"

      - name: Print Date
        run: date
      
      - name: List Directory Content
        run: ls -l
